repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: rust-style
        name: Rust style
        description: Run cargo fmt on files included in the commit. rustfmt should be installed before-hand.
        entry: cargo fmt --all -- --check
        pass_filenames: true
        types: [file, rust]
        language: system
    -   id: rust-lint
        name: Rust lint
        description: Run cargo clippy on files included in the commit. clippy should be installed before-hand.
        entry: cargo clippy --all --all-targets -- -D warnings
        pass_filenames: false
        types: [file, rust]
        language: system
