[package]
name = "composer"
version = "0.1.0"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "rpc" ]
rpc = []

[build-dependencies]
tonic-build = "0.5.2"
prost-build = "0.8.0"

[dependencies]
once_cell = "1.8.0"
tokio = { version = "1.12.0", features = [ "full" ] }
futures = "0.3.17"
tonic = "0.5.2"
crossbeam = "0.8.1"
ipnetwork = "0.18.0"
bollard = "0.11.0"
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
prost = "0.8.0"
prost-derive = "0.8.0"
prost-types = "0.8.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_derive = "1.0.130"
serde_json = "1.0.68"